# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/Pmod_TC1/Pmod_TC1.srcs/sources_1/bd/Pmod_TC1/ip/Pmod_TC1_lmb_bram_0/Pmod_TC1_lmb_bram_0.xci
# IP: The module: 'Pmod_TC1_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/Pmod_TC1/Pmod_TC1.gen/sources_1/bd/Pmod_TC1/ip/Pmod_TC1_lmb_bram_0/Pmod_TC1_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pmod_TC1_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/Pmod_TC1/Pmod_TC1.srcs/sources_1/bd/Pmod_TC1/ip/Pmod_TC1_lmb_bram_0/Pmod_TC1_lmb_bram_0.xci
# IP: The module: 'Pmod_TC1_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/Pmod_TC1/Pmod_TC1.gen/sources_1/bd/Pmod_TC1/ip/Pmod_TC1_lmb_bram_0/Pmod_TC1_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pmod_TC1_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
