# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.srcs/sources_1/bd/GPIO/ip/GPIO_xbar_0/GPIO_xbar_0.xci
# IP: The module: 'GPIO_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_xbar_0/GPIO_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.srcs/sources_1/bd/GPIO/ip/GPIO_xbar_0/GPIO_xbar_0.xci
# IP: The module: 'GPIO_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_xbar_0/GPIO_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
