# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pmod_TC1_Const.xdc

# Block Designs: bd/Pmod_TC1/Pmod_TC1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1 || ORIG_REF_NAME==Pmod_TC1} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_clk_wiz_0_0/Pmod_TC1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_clk_wiz_0_0 || ORIG_REF_NAME==Pmod_TC1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_axi_uartlite_0_0/Pmod_TC1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_axi_uartlite_0_0 || ORIG_REF_NAME==Pmod_TC1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_mig_7series_0_0/Pmod_TC1_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_mig_7series_0_0 || ORIG_REF_NAME==Pmod_TC1_mig_7series_0_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_microblaze_0_0/Pmod_TC1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_microblaze_0_0 || ORIG_REF_NAME==Pmod_TC1_microblaze_0_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_dlmb_v10_0/Pmod_TC1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_dlmb_v10_0 || ORIG_REF_NAME==Pmod_TC1_dlmb_v10_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_ilmb_v10_0/Pmod_TC1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_ilmb_v10_0 || ORIG_REF_NAME==Pmod_TC1_ilmb_v10_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_dlmb_bram_if_cntlr_0/Pmod_TC1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Pmod_TC1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_ilmb_bram_if_cntlr_0/Pmod_TC1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Pmod_TC1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_lmb_bram_0/Pmod_TC1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_lmb_bram_0 || ORIG_REF_NAME==Pmod_TC1_lmb_bram_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_mdm_1_0/Pmod_TC1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_mdm_1_0 || ORIG_REF_NAME==Pmod_TC1_mdm_1_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_rst_mig_7series_0_83M_0/Pmod_TC1_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==Pmod_TC1_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_xbar_0/Pmod_TC1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_xbar_0 || ORIG_REF_NAME==Pmod_TC1_xbar_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_microblaze_0_axi_periph_0/Pmod_TC1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Pmod_TC1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_axi_smc_0/Pmod_TC1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_axi_smc_0 || ORIG_REF_NAME==Pmod_TC1_axi_smc_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_PmodTC1_0_0/Pmod_TC1_PmodTC1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_PmodTC1_0_0 || ORIG_REF_NAME==Pmod_TC1_PmodTC1_0_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/Pmod_TC1/Pmod_TC1.gen/sources_1/bd/Pmod_TC1/Pmod_TC1_ooc.xdc
