# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pmod_AD2_Cons.xdc

# Block Designs: bd/Pmod_AD2/Pmod_AD2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2 || ORIG_REF_NAME==Pmod_AD2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_processing_system7_0_0/Pmod_AD2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_processing_system7_0_0 || ORIG_REF_NAME==Pmod_AD2_processing_system7_0_0} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_PmodAD2_0_0/Pmod_AD2_PmodAD2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_PmodAD2_0_0 || ORIG_REF_NAME==Pmod_AD2_PmodAD2_0_0} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_auto_pc_0/Pmod_AD2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_auto_pc_0 || ORIG_REF_NAME==Pmod_AD2_auto_pc_0} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_ps7_0_axi_periph_0/Pmod_AD2_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_ps7_0_axi_periph_0 || ORIG_REF_NAME==Pmod_AD2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_rst_ps7_0_50M_0/Pmod_AD2_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_rst_ps7_0_50M_0 || ORIG_REF_NAME==Pmod_AD2_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Pmod_AD2/Pmod_AD2.gen/sources_1/bd/Pmod_AD2/Pmod_AD2_ooc.xdc
