# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pmod_TC1_Const.xdc

# Block Designs: bd/Pmod_TC1/Pmod_TC1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1 || ORIG_REF_NAME==Pmod_TC1} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_processing_system7_0_0/Pmod_TC1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_processing_system7_0_0 || ORIG_REF_NAME==Pmod_TC1_processing_system7_0_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_PmodTC1_0_0/Pmod_TC1_PmodTC1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_PmodTC1_0_0 || ORIG_REF_NAME==Pmod_TC1_PmodTC1_0_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_auto_pc_0/Pmod_TC1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_auto_pc_0 || ORIG_REF_NAME==Pmod_TC1_auto_pc_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_ps7_0_axi_periph_0/Pmod_TC1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_ps7_0_axi_periph_0 || ORIG_REF_NAME==Pmod_TC1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pmod_TC1/ip/Pmod_TC1_rst_ps7_0_50M_0/Pmod_TC1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_TC1_rst_ps7_0_50M_0 || ORIG_REF_NAME==Pmod_TC1_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Pmod_TC1/Pmod_TC1.gen/sources_1/bd/Pmod_TC1/Pmod_TC1_ooc.xdc
