# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/GPIO/GPIO.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO || ORIG_REF_NAME==GPIO} -quiet] -quiet

# IP: bd/GPIO/ip/GPIO_processing_system7_0_0/GPIO_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_processing_system7_0_0 || ORIG_REF_NAME==GPIO_processing_system7_0_0} -quiet] -quiet

# IP: bd/GPIO/ip/GPIO_axi_gpio_0_1/GPIO_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_axi_gpio_0_1 || ORIG_REF_NAME==GPIO_axi_gpio_0_1} -quiet] -quiet

# IP: bd/GPIO/ip/GPIO_auto_pc_0/GPIO_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_auto_pc_0 || ORIG_REF_NAME==GPIO_auto_pc_0} -quiet] -quiet

# IP: bd/GPIO/ip/GPIO_ps7_0_axi_periph_0/GPIO_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_ps7_0_axi_periph_0 || ORIG_REF_NAME==GPIO_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/GPIO/ip/GPIO_rst_ps7_0_100M_0/GPIO_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_rst_ps7_0_100M_0 || ORIG_REF_NAME==GPIO_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Pynq Z1/GPIO/GPIO/GPIO.gen/sources_1/bd/GPIO/GPIO_ooc.xdc
