# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.srcs/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_xbar_0/Sensors_OLED_xbar_0.xci
# IP: The module: 'Sensors_OLED_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_xbar_0/Sensors_OLED_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensors_OLED_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.srcs/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_xbar_0/Sensors_OLED_xbar_0.xci
# IP: The module: 'Sensors_OLED_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_xbar_0/Sensors_OLED_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensors_OLED_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
