# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pmod_OLED_Const.xdc

# Block Designs: bd/Pmod_OLED/Pmod_OLED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED || ORIG_REF_NAME==Pmod_OLED} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_processing_system7_0_0/Pmod_OLED_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_processing_system7_0_0 || ORIG_REF_NAME==Pmod_OLED_processing_system7_0_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_PmodOLED_0_0/Pmod_OLED_PmodOLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_PmodOLED_0_0 || ORIG_REF_NAME==Pmod_OLED_PmodOLED_0_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_xbar_0/Pmod_OLED_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_xbar_0 || ORIG_REF_NAME==Pmod_OLED_xbar_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_auto_pc_0/Pmod_OLED_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_auto_pc_0 || ORIG_REF_NAME==Pmod_OLED_auto_pc_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_ps7_0_axi_periph_0/Pmod_OLED_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_ps7_0_axi_periph_0 || ORIG_REF_NAME==Pmod_OLED_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_rst_ps7_0_50M_0/Pmod_OLED_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_rst_ps7_0_50M_0 || ORIG_REF_NAME==Pmod_OLED_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Pmod_OLED/Pmod_OLED.gen/sources_1/bd/Pmod_OLED/Pmod_OLED_ooc.xdc
