# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Sensors_Const.xdc

# Block Designs: bd/Sensors/Sensors.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors || ORIG_REF_NAME==Sensors} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_PmodAD2_0_0/Sensors_PmodAD2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_PmodAD2_0_0 || ORIG_REF_NAME==Sensors_PmodAD2_0_0} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_PmodTC1_0_0/Sensors_PmodTC1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_PmodTC1_0_0 || ORIG_REF_NAME==Sensors_PmodTC1_0_0} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_processing_system7_0_0/Sensors_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_processing_system7_0_0 || ORIG_REF_NAME==Sensors_processing_system7_0_0} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_xbar_0/Sensors_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_xbar_0 || ORIG_REF_NAME==Sensors_xbar_0} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_ps7_0_axi_periph_0/Sensors_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ps7_0_axi_periph_0 || ORIG_REF_NAME==Sensors_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_rst_ps7_0_100M_0/Sensors_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_rst_ps7_0_100M_0 || ORIG_REF_NAME==Sensors_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_auto_pc_2/Sensors_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_auto_pc_2 || ORIG_REF_NAME==Sensors_auto_pc_2} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_auto_pc_0/Sensors_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_auto_pc_0 || ORIG_REF_NAME==Sensors_auto_pc_0} -quiet] -quiet

# IP: bd/Sensors/ip/Sensors_auto_pc_1/Sensors_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_auto_pc_1 || ORIG_REF_NAME==Sensors_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Pynq Z1/Sensors/Sensors.gen/sources_1/bd/Sensors/Sensors_ooc.xdc
