#Pmod JB connects to Pmod AD2
set_property PACKAGE_PIN V8 [get_ports Pmod_out_0_pin1_io]
set_property PACKAGE_PIN W8 [get_ports Pmod_out_0_pin2_io]
set_property PACKAGE_PIN U7 [get_ports Pmod_out_0_pin3_io]
set_property PACKAGE_PIN V7 [get_ports Pmod_out_0_pin4_io]
set_property PACKAGE_PIN Y7 [get_ports Pmod_out_0_pin7_io]
set_property PACKAGE_PIN Y6 [get_ports Pmod_out_0_pin8_io]
set_property PACKAGE_PIN V6 [get_ports Pmod_out_0_pin9_io]
set_property PACKAGE_PIN W6 [get_ports Pmod_out_0_pin10_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin1_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin2_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin3_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin4_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin7_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin8_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin9_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_0_pin10_io]
set_property SLEW SLOW [get_ports Pmod_out_0_pin3_io]
set_property PULLUP true [get_ports Pmod_out_0_pin3_io]
set_property PULLUP true [get_ports Pmod_out_0_pin4_io]

# Pmod JC connects to Pmod TC1
set_property PACKAGE_PIN V15 [get_ports Pmod_out_2_pin1_io]
set_property PACKAGE_PIN W15 [get_ports Pmod_out_2_pin2_io]
set_property PACKAGE_PIN T11 [get_ports Pmod_out_2_pin3_io]
set_property PACKAGE_PIN T10 [get_ports Pmod_out_2_pin4_io]
set_property PACKAGE_PIN W14 [get_ports Pmod_out_2_pin7_io]
set_property PACKAGE_PIN Y14 [get_ports Pmod_out_2_pin8_io]
set_property PACKAGE_PIN T12 [get_ports Pmod_out_2_pin9_io]
set_property PACKAGE_PIN U12 [get_ports Pmod_out_2_pin10_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_2_pin1_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_2_pin2_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_2_pin3_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_2_pin4_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_2_pin7_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_2_pin8_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_2_pin9_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_2_pin10_io]

#Pmod JD connects to Pmod OLED
set_property PACKAGE_PIN T14 [get_ports Pmod_out_1_pin1_io]
set_property PACKAGE_PIN T15 [get_ports Pmod_out_1_pin2_io]
set_property PACKAGE_PIN P14 [get_ports Pmod_out_1_pin3_io]
set_property PACKAGE_PIN R14 [get_ports Pmod_out_1_pin4_io]
set_property PACKAGE_PIN U14 [get_ports Pmod_out_1_pin7_io]
set_property PACKAGE_PIN U15 [get_ports Pmod_out_1_pin8_io]
set_property PACKAGE_PIN V17 [get_ports Pmod_out_1_pin9_io]
set_property PACKAGE_PIN V18 [get_ports Pmod_out_1_pin10_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_1_pin1_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_1_pin2_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_1_pin3_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_1_pin4_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_1_pin7_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_1_pin8_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_1_pin9_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_1_pin10_io]