# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/UART/UART.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART || ORIG_REF_NAME==UART} -quiet] -quiet

# IP: bd/UART/ip/UART_clk_wiz_0_0/UART_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_clk_wiz_0_0 || ORIG_REF_NAME==UART_clk_wiz_0_0} -quiet] -quiet

# IP: bd/UART/ip/UART_mig_7series_0_0/UART_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_mig_7series_0_0 || ORIG_REF_NAME==UART_mig_7series_0_0} -quiet] -quiet

# IP: bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_axi_uartlite_0_0 || ORIG_REF_NAME==UART_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/UART/ip/UART_microblaze_0_0/UART_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_microblaze_0_0 || ORIG_REF_NAME==UART_microblaze_0_0} -quiet] -quiet

# IP: bd/UART/ip/UART_dlmb_v10_0/UART_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_dlmb_v10_0 || ORIG_REF_NAME==UART_dlmb_v10_0} -quiet] -quiet

# IP: bd/UART/ip/UART_ilmb_v10_0/UART_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_ilmb_v10_0 || ORIG_REF_NAME==UART_ilmb_v10_0} -quiet] -quiet

# IP: bd/UART/ip/UART_dlmb_bram_if_cntlr_0/UART_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==UART_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/UART/ip/UART_ilmb_bram_if_cntlr_0/UART_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==UART_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/UART/ip/UART_lmb_bram_0/UART_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_lmb_bram_0 || ORIG_REF_NAME==UART_lmb_bram_0} -quiet] -quiet

# IP: bd/UART/ip/UART_mdm_1_0/UART_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_mdm_1_0 || ORIG_REF_NAME==UART_mdm_1_0} -quiet] -quiet

# IP: bd/UART/ip/UART_rst_clk_wiz_0_166M_0/UART_rst_clk_wiz_0_166M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_rst_clk_wiz_0_166M_0 || ORIG_REF_NAME==UART_rst_clk_wiz_0_166M_0} -quiet] -quiet

# IP: bd/UART/ip/UART_microblaze_0_axi_periph_0/UART_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_microblaze_0_axi_periph_0 || ORIG_REF_NAME==UART_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/UART/ip/UART_axi_smc_0/UART_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_axi_smc_0 || ORIG_REF_NAME==UART_axi_smc_0} -quiet] -quiet

# IP: bd/UART/ip/UART_rst_mig_7series_0_83M_0/UART_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==UART_rst_mig_7series_0_83M_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.gen/sources_1/bd/UART/UART_ooc.xdc
