# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pmod_OLED_Const.xdc

# Block Designs: bd/Pmod_OLED/Pmod_OLED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED || ORIG_REF_NAME==Pmod_OLED} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_clk_wiz_0_0/Pmod_OLED_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_clk_wiz_0_0 || ORIG_REF_NAME==Pmod_OLED_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_mig_7series_0_0/Pmod_OLED_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_mig_7series_0_0 || ORIG_REF_NAME==Pmod_OLED_mig_7series_0_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_axi_uartlite_0_0/Pmod_OLED_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_axi_uartlite_0_0 || ORIG_REF_NAME==Pmod_OLED_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_microblaze_0_0/Pmod_OLED_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_microblaze_0_0 || ORIG_REF_NAME==Pmod_OLED_microblaze_0_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_PmodOLED_0_0/Pmod_OLED_PmodOLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_PmodOLED_0_0 || ORIG_REF_NAME==Pmod_OLED_PmodOLED_0_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_dlmb_v10_0/Pmod_OLED_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_dlmb_v10_0 || ORIG_REF_NAME==Pmod_OLED_dlmb_v10_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_ilmb_v10_0/Pmod_OLED_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_ilmb_v10_0 || ORIG_REF_NAME==Pmod_OLED_ilmb_v10_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_dlmb_bram_if_cntlr_0/Pmod_OLED_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Pmod_OLED_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_ilmb_bram_if_cntlr_0/Pmod_OLED_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Pmod_OLED_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_lmb_bram_0/Pmod_OLED_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_lmb_bram_0 || ORIG_REF_NAME==Pmod_OLED_lmb_bram_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_mdm_1_0/Pmod_OLED_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_mdm_1_0 || ORIG_REF_NAME==Pmod_OLED_mdm_1_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_rst_mig_7series_0_83M_0/Pmod_OLED_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==Pmod_OLED_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_xbar_0/Pmod_OLED_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_xbar_0 || ORIG_REF_NAME==Pmod_OLED_xbar_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_microblaze_0_axi_periph_0/Pmod_OLED_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Pmod_OLED_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Pmod_OLED/ip/Pmod_OLED_axi_smc_0/Pmod_OLED_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_OLED_axi_smc_0 || ORIG_REF_NAME==Pmod_OLED_axi_smc_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/Pmod_OLED/Pmod_OLED.gen/sources_1/bd/Pmod_OLED/Pmod_OLED_ooc.xdc
