# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Sensors_OLED.xdc

# Block Designs: bd/Sensors_OLED/Sensors_OLED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED || ORIG_REF_NAME==Sensors_OLED} -quiet] -quiet

# IP: bd/Sensors_OLED/ip/Sensors_OLED_processing_system7_0_0/Sensors_OLED_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED_processing_system7_0_0 || ORIG_REF_NAME==Sensors_OLED_processing_system7_0_0} -quiet] -quiet

# IP: bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/Sensors_OLED_PmodAD2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED_PmodAD2_0_0 || ORIG_REF_NAME==Sensors_OLED_PmodAD2_0_0} -quiet] -quiet

# IP: bd/Sensors_OLED/ip/Sensors_OLED_PmodOLED_0_0/Sensors_OLED_PmodOLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED_PmodOLED_0_0 || ORIG_REF_NAME==Sensors_OLED_PmodOLED_0_0} -quiet] -quiet

# IP: bd/Sensors_OLED/ip/Sensors_OLED_PmodTC1_0_0/Sensors_OLED_PmodTC1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED_PmodTC1_0_0 || ORIG_REF_NAME==Sensors_OLED_PmodTC1_0_0} -quiet] -quiet

# IP: bd/Sensors_OLED/ip/Sensors_OLED_xbar_0/Sensors_OLED_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED_xbar_0 || ORIG_REF_NAME==Sensors_OLED_xbar_0} -quiet] -quiet

# IP: bd/Sensors_OLED/ip/Sensors_OLED_auto_pc_0/Sensors_OLED_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED_auto_pc_0 || ORIG_REF_NAME==Sensors_OLED_auto_pc_0} -quiet] -quiet

# IP: bd/Sensors_OLED/ip/Sensors_OLED_ps7_0_axi_periph_0/Sensors_OLED_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED_ps7_0_axi_periph_0 || ORIG_REF_NAME==Sensors_OLED_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Sensors_OLED/ip/Sensors_OLED_rst_ps7_0_50M_0/Sensors_OLED_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_OLED_rst_ps7_0_50M_0 || ORIG_REF_NAME==Sensors_OLED_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/Sensors_OLED_ooc.xdc
