# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/Pmod_AD2/Pmod_AD2.srcs/sources_1/bd/Pmod_AD2/ip/Pmod_AD2_lmb_bram_2/Pmod_AD2_lmb_bram_2.xci
# IP: The module: 'Pmod_AD2_lmb_bram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/Pmod_AD2/Pmod_AD2.gen/sources_1/bd/Pmod_AD2/ip/Pmod_AD2_lmb_bram_2/Pmod_AD2_lmb_bram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pmod_AD2_lmb_bram_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/Pmod_AD2/Pmod_AD2.srcs/sources_1/bd/Pmod_AD2/ip/Pmod_AD2_lmb_bram_2/Pmod_AD2_lmb_bram_2.xci
# IP: The module: 'Pmod_AD2_lmb_bram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/Pmod_AD2/Pmod_AD2.gen/sources_1/bd/Pmod_AD2/ip/Pmod_AD2_lmb_bram_2/Pmod_AD2_lmb_bram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pmod_AD2_lmb_bram_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
