# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/luisr/Desktop/digilent-xdc-master/Arty-A7-100-Master.xdc

# XDC: new/Pmod_AD2_Const.xdc

# Block Designs: bd/Pmod_AD2/Pmod_AD2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2 || ORIG_REF_NAME==Pmod_AD2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_clk_wiz_0_2/Pmod_AD2_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_clk_wiz_0_2 || ORIG_REF_NAME==Pmod_AD2_clk_wiz_0_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_mig_7series_0_1/Pmod_AD2_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_mig_7series_0_1 || ORIG_REF_NAME==Pmod_AD2_mig_7series_0_1} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_axi_uartlite_0_2/Pmod_AD2_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_axi_uartlite_0_2 || ORIG_REF_NAME==Pmod_AD2_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_PmodAD2_0_2/Pmod_AD2_PmodAD2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_PmodAD2_0_2 || ORIG_REF_NAME==Pmod_AD2_PmodAD2_0_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_microblaze_0_2/Pmod_AD2_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_microblaze_0_2 || ORIG_REF_NAME==Pmod_AD2_microblaze_0_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_dlmb_v10_2/Pmod_AD2_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_dlmb_v10_2 || ORIG_REF_NAME==Pmod_AD2_dlmb_v10_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_ilmb_v10_2/Pmod_AD2_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_ilmb_v10_2 || ORIG_REF_NAME==Pmod_AD2_ilmb_v10_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_dlmb_bram_if_cntlr_2/Pmod_AD2_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==Pmod_AD2_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_ilmb_bram_if_cntlr_2/Pmod_AD2_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==Pmod_AD2_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_lmb_bram_2/Pmod_AD2_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_lmb_bram_2 || ORIG_REF_NAME==Pmod_AD2_lmb_bram_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_mdm_1_2/Pmod_AD2_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_mdm_1_2 || ORIG_REF_NAME==Pmod_AD2_mdm_1_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_rst_mig_7series_0_83M_2/Pmod_AD2_rst_mig_7series_0_83M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_rst_mig_7series_0_83M_2 || ORIG_REF_NAME==Pmod_AD2_rst_mig_7series_0_83M_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_xbar_2/Pmod_AD2_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_xbar_2 || ORIG_REF_NAME==Pmod_AD2_xbar_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_microblaze_0_axi_periph_2/Pmod_AD2_microblaze_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_microblaze_0_axi_periph_2 || ORIG_REF_NAME==Pmod_AD2_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/Pmod_AD2/ip/Pmod_AD2_axi_smc_2/Pmod_AD2_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pmod_AD2_axi_smc_2 || ORIG_REF_NAME==Pmod_AD2_axi_smc_2} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/Pmod_AD2/Pmod_AD2.gen/sources_1/bd/Pmod_AD2/Pmod_AD2_ooc.xdc
