# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Pynq Z1/GPIO/GPIO/GPIO.srcs/sources_1/bd/GPIO/ip/GPIO_auto_pc_0/GPIO_auto_pc_0.xci
# IP: The module: 'GPIO_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Pynq Z1/GPIO/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_auto_pc_0/GPIO_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Pynq Z1/GPIO/GPIO/GPIO.srcs/sources_1/bd/GPIO/ip/GPIO_auto_pc_0/GPIO_auto_pc_0.xci
# IP: The module: 'GPIO_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Pynq Z1/GPIO/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_auto_pc_0/GPIO_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
