# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/UART_DDR/UART_DDR/UART_DDR.srcs/sources_1/bd/UART_DDR/ip/UART_DDR_mdm_1_0/UART_DDR_mdm_1_0.xci
# IP: The module: 'UART_DDR_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/UART_DDR/UART_DDR/UART_DDR.gen/sources_1/bd/UART_DDR/ip/UART_DDR_mdm_1_0/UART_DDR_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DDR_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/UART_DDR/UART_DDR/UART_DDR.gen/sources_1/bd/UART_DDR/ip/UART_DDR_mdm_1_0/UART_DDR_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DDR_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/UART_DDR/UART_DDR/UART_DDR.srcs/sources_1/bd/UART_DDR/ip/UART_DDR_mdm_1_0/UART_DDR_mdm_1_0.xci
# IP: The module: 'UART_DDR_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/UART_DDR/UART_DDR/UART_DDR.gen/sources_1/bd/UART_DDR/ip/UART_DDR_mdm_1_0/UART_DDR_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DDR_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Arty A7-100T/UART_DDR/UART_DDR/UART_DDR.gen/sources_1/bd/UART_DDR/ip/UART_DDR_mdm_1_0/UART_DDR_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DDR_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
