# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.srcs/sources_1/bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0.xci
# IP: The module: 'UART_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.gen/sources_1/bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.gen/sources_1/bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.gen/sources_1/bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.srcs/sources_1/bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0.xci
# IP: The module: 'UART_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.gen/sources_1/bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.gen/sources_1/bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Arty A7-100T/UART/UART/UART.gen/sources_1/bd/UART/ip/UART_axi_uartlite_0_0/UART_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
