# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/UART_DDR/UART_DDR.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_DDR || ORIG_REF_NAME==UART_DDR} -quiet] -quiet

# IP: bd/UART_DDR/ip/UART_DDR_processing_system7_0_0/UART_DDR_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_DDR_processing_system7_0_0 || ORIG_REF_NAME==UART_DDR_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Pynq Z1/UART_DDR/UART_DDR.gen/sources_1/bd/UART_DDR/UART_DDR_ooc.xdc
