# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.srcs/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/Sensors_OLED_PmodAD2_0_0.xci
# IP: The module: 'Sensors_OLED_PmodAD2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodAD2_axi_iic_0_0 || ORIG_REF_NAME==PmodAD2_axi_iic_0_0} -quiet] -quiet

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/PmodAD2_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodAD2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodAD2_pmod_bridge_0_0} -quiet] -quiet

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_xlconstant_0_0/PmodAD2_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodAD2_xlconstant_0_0 || ORIG_REF_NAME==PmodAD2_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodAD2_axi_iic_0_0 || ORIG_REF_NAME==PmodAD2_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0_ooc.xdc

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/Sensors_OLED_PmodAD2_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensors_OLED_PmodAD2_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensors_OLED_PmodAD2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/PmodAD2_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodAD2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodAD2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# IP: C:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.srcs/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/Sensors_OLED_PmodAD2_0_0.xci
# IP: The module: 'Sensors_OLED_PmodAD2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodAD2_axi_iic_0_0 || ORIG_REF_NAME==PmodAD2_axi_iic_0_0} -quiet] -quiet

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/PmodAD2_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodAD2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodAD2_pmod_bridge_0_0} -quiet] -quiet

# IP: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_xlconstant_0_0/PmodAD2_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodAD2_xlconstant_0_0 || ORIG_REF_NAME==PmodAD2_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodAD2_axi_iic_0_0 || ORIG_REF_NAME==PmodAD2_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_axi_iic_0_0/PmodAD2_axi_iic_0_0_ooc.xdc

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/Sensors_OLED_PmodAD2_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensors_OLED_PmodAD2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensors_OLED_PmodAD2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/PmodAD2_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodAD2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodAD2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/luisr/Desktop/FPGA/Hardware/Zybo Z7-20/Sensors_OLED/Sensors_OLED.gen/sources_1/bd/Sensors_OLED/ip/Sensors_OLED_PmodAD2_0_0/src/PmodAD2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
