# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.srcs/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/GPIO_ddr4_0_0.xci
# IP: The module: 'GPIO_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_1/GPIO_ddr4_0_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_ddr4_0_0_phy || ORIG_REF_NAME==GPIO_ddr4_0_0_phy} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_0/GPIO_ddr4_0_0_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==GPIO_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/bd_60fd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd || ORIG_REF_NAME==bd_60fd} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_0/bd_60fd_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_microblaze_I_0 || ORIG_REF_NAME==bd_60fd_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_1/bd_60fd_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_rst_0_0 || ORIG_REF_NAME==bd_60fd_rst_0_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_2/bd_60fd_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_ilmb_0 || ORIG_REF_NAME==bd_60fd_ilmb_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_3/bd_60fd_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_dlmb_0 || ORIG_REF_NAME==bd_60fd_dlmb_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_4/bd_60fd_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_dlmb_cntlr_0 || ORIG_REF_NAME==bd_60fd_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_5/bd_60fd_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_ilmb_cntlr_0 || ORIG_REF_NAME==bd_60fd_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_6/bd_60fd_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_lmb_bram_I_0 || ORIG_REF_NAME==bd_60fd_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_7/bd_60fd_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_60fd_second_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_8/bd_60fd_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_60fd_second_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_9/bd_60fd_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_60fd_second_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_10/bd_60fd_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_iomodule_0_0 || ORIG_REF_NAME==bd_60fd_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_1/par/GPIO_ddr4_0_0_phy_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_0/bd_60fd_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_microblaze_I_0 || ORIG_REF_NAME==bd_60fd_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_0/bd_60fd_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_1/bd_60fd_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_rst_0_0 || ORIG_REF_NAME==bd_60fd_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_1/bd_60fd_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_rst_0_0 || ORIG_REF_NAME==bd_60fd_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_2/bd_60fd_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_ilmb_0 || ORIG_REF_NAME==bd_60fd_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_3/bd_60fd_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_dlmb_0 || ORIG_REF_NAME==bd_60fd_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_6/bd_60fd_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_9/bd_60fd_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_10/bd_60fd_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_iomodule_0_0 || ORIG_REF_NAME==bd_60fd_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/bd_60fd_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_0/GPIO_ddr4_0_0_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==GPIO_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_0/GPIO_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/GPIO_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/par/GPIO_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.srcs/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/GPIO_ddr4_0_0.xci
# IP: The module: 'GPIO_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_1/GPIO_ddr4_0_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_ddr4_0_0_phy || ORIG_REF_NAME==GPIO_ddr4_0_0_phy} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_0/GPIO_ddr4_0_0_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==GPIO_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/bd_60fd.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd || ORIG_REF_NAME==bd_60fd} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_0/bd_60fd_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_microblaze_I_0 || ORIG_REF_NAME==bd_60fd_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_1/bd_60fd_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_rst_0_0 || ORIG_REF_NAME==bd_60fd_rst_0_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_2/bd_60fd_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_ilmb_0 || ORIG_REF_NAME==bd_60fd_ilmb_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_3/bd_60fd_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_dlmb_0 || ORIG_REF_NAME==bd_60fd_dlmb_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_4/bd_60fd_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_dlmb_cntlr_0 || ORIG_REF_NAME==bd_60fd_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_5/bd_60fd_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_ilmb_cntlr_0 || ORIG_REF_NAME==bd_60fd_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_6/bd_60fd_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_lmb_bram_I_0 || ORIG_REF_NAME==bd_60fd_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_7/bd_60fd_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_60fd_second_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_8/bd_60fd_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_60fd_second_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_9/bd_60fd_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_60fd_second_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_10/bd_60fd_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_60fd_iomodule_0_0 || ORIG_REF_NAME==bd_60fd_iomodule_0_0} -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_1/par/GPIO_ddr4_0_0_phy_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_0/bd_60fd_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_microblaze_I_0 || ORIG_REF_NAME==bd_60fd_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_0/bd_60fd_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_1/bd_60fd_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_rst_0_0 || ORIG_REF_NAME==bd_60fd_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_1/bd_60fd_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_rst_0_0 || ORIG_REF_NAME==bd_60fd_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_2/bd_60fd_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_ilmb_0 || ORIG_REF_NAME==bd_60fd_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_3/bd_60fd_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_dlmb_0 || ORIG_REF_NAME==bd_60fd_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_6/bd_60fd_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_9/bd_60fd_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/ip/ip_10/bd_60fd_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_60fd_iomodule_0_0 || ORIG_REF_NAME==bd_60fd_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/bd_0/bd_60fd_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_0/GPIO_ddr4_0_0_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==GPIO_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==GPIO_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/ip_0/GPIO_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/GPIO_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lurivera/Desktop/KCU105/GPIO/GPIO.gen/sources_1/bd/GPIO/ip/GPIO_ddr4_0_0/par/GPIO_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
